In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
zerodarr = np.array([1])
print(type(zerodarr))

<class 'numpy.ndarray'>


In [12]:
twodarr = np.array([[1,2,3],[4,5,6]])
print(twodarr)

[[1 2 3]
 [4 5 6]]


In [20]:
threeDArr = np.array([[1,2,3],[4,5,6],[7,9,8]])
print(threeDArr)
print(threeDArr[0][2])

[[1 2 3]
 [4 5 6]
 [7 9 8]]
3


In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [12, 5, 6]]])

print(arr)
print(arr[1][1][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [12  5  6]]]
12


In [16]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
