In [1]:
import numpy as np

In [4]:
arr = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
zerodarr = np.array(23)
print(zerodarr)

23


In [23]:
oneDarr = np.array([[[1,2,3],[2,4,6],[3,4,3]]])
print(oneDarr)
print(oneDarr.ndim)

[[[1 2 3]
  [2 4 6]
  [3 4 3]]]
3


In [32]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d)

0
1
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [31]:
print(d[1][0][0])

1


In [33]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print()

2nd element on 1st row:  2
