lets assume we have data as below;- x = [1, 1, 1, 1, 0, 0, 0, 0, 0] y = [0, 0, 1, 1, 1, 1, 0, 0, 0]

In [14]:
#import modules
import numpy as np
from numpy import dot
from numpy.linalg import norm

#define arrays
x = np.array([1, 1, 1, 1, 0, 0, 0, 0, 0]) 
y = np.array([0, 0, 1, 1, 1, 1, 0, 0, 0])

#calculate Cosine Similarity python
result = dot(x, y)/(norm(x)*norm(y))

print("The Cosine Similarity between two vectors is: ",result)

The Cosine Similarity between two vectors is:  0.5


In the above code, we import numpy package to use dot() and norm() functions to calculate Cosine Similarity in python.

Using dot(x, y)/(norm(x)*norm(y)), we calculate the cosine similarity between two vectors x & y in python.

we will calculate Python Cosine similarity between two randomly generated arrays of the same length in python with the given below code.

In [17]:
#import modules
import numpy as np
from numpy import dot
from numpy.linalg import norm

#define arrays
x = np.random.randint(10, size=100)
y = np.random.randint(10, size=100)


# Calculate Cosine Similarity Python
result = dot(x, y)/(norm(x)*norm(y))

print("The Cosine Similarity between two vectors is: ",result)

The Cosine Similarity between two vectors is:  0.7056435497121479


In [4]:
import numpy as np

def cosine_similarity(x, y):
    
    # Ensure length of x and y are the same
    if len(x) != len(y) :
        return None
    
    # Compute the dot product between x and y
    dot_product = np.dot(x, y)
    
    # Compute the L2 norms (magnitudes) of x and y
    magnitude_x = np.sqrt(np.sum(x**2)) 
    magnitude_y = np.sqrt(np.sum(y**2))
    
    # Compute the cosine similarity
    cosine_similarity = dot_product / (magnitude_x * magnitude_y)
    
    return cosine_similarity

In [5]:
corpus = [  'data science is one of the most important fields of science',
            'this is one of the best data science courses',
            'data scientists analyze data'   ]

Using sklearn, we'll vectorize the documents:

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

# Create a matrix to represent the corpus
X = CountVectorizer().fit_transform(corpus).toarray()

print(X)

[[0 0 0 1 1 1 1 1 2 1 2 0 1 0]
 [0 1 1 1 0 0 1 0 1 1 1 0 1 1]
 [1 0 0 2 0 0 0 0 0 0 0 1 0 0]]


With the above vectors, we can now compute cosine similarity between the corpus documents:

In [21]:
cos_sim_1_2 = cosine_similarity(X[0, :], X[1, :])
cos_sim_1_3 = cosine_similarity(X[0, :], X[2, :])
cos_sim_2_3 = cosine_similarity(X[1, :], X[2, :])

print('Cosine Similarity between: ')
print('\tDocument 1 and Document 2: ', cos_sim_1_2)
print('\tDocument 1 and Document 3: ', cos_sim_1_3)
print('\tDocument 2 and Document 3: ', cos_sim_2_3)

Cosine Similarity between: 
	Document 1 and Document 2:  0.6885303726590962
	Document 1 and Document 3:  0.21081851067789195
	Document 2 and Document 3:  0.2721655269759087


### Eucludein Distance
The NumPy module has a norm() method, which can be used to find the required distance when the data is provided in the form of an array.

The norm() method returns the vector norm of an array.

In [22]:
 #Python code to find Euclidean distance
# using linalg.norm()

# Import NumPy Library
import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((4, 4, 2))
point2 = np.array((1, 2, 1))

# calculate Euclidean distance
# using linalg.norm() method
dist = np.linalg.norm(point1 - point2)

# printing Euclidean distance
print(dist)

3.7416573867739413


### Method 2: Using dot() and sqrt() methods
We can leverage the NumPy dot() method for finding the dot product of the difference of points, and by doing the square root of the output returned by the dot() method, we will be getting the Euclidean distance. 

In [9]:
# Python code to find Euclidean distance
# using dot() and sqrt() methods

# Import NumPy Library
import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((4, 4, 2))
point2 = np.array((1, 2, 1))

# subtracting both the vectors
temp = point1 - point2
 
# Perform dot product
# and do the square root
dist = np.sqrt(np.dot(temp.T, temp))
 
# printing Euclidean distance
print(dist)

3.7416573867739413


### Method 3: Using square() and sum() methods
Another alternate way is to apply the mathematical formula (d = √[(x2 – x1)2 + (y2 – y1)2]) using the NumPy Module to Calculate Euclidean Distance in Python

The sum() function will return the sum of elements, and we will apply the square root to the returned element to get the Euclidean distance.

In [10]:
# Python code to find Euclidean distance
# using square() and sum() methods

# Import NumPy Library
import numpy as np

# initializing points in
# numpy arrays
point1 = np.array((4, 4, 2))
point2 = np.array((1, 2, 1))

# finding sum of squares
sum_vectors = np.sum(np.square(point1 - point2))
 
# perform the squareroot and
# print Euclidean distance
print(np.sqrt(sum_vectors))

3.7416573867739413


### Method 4: Using distance.euclidean() from SciPy Module
We discussed several methods to Calculate Euclidean distance in Python using the NumPy module. These methods can be slower when it comes to performance, and hence we can use the SciPy library, which is much more performance efficient.

The SciPy module is mainly used for mathematical and scientific calculations. It has a built-in distance.euclidean() method that returns the Euclidean Distance between two points.

In [11]:
# Python code to find Euclidean distance
# using distance.euclidean() method

# Import SciPi Library
from scipy.spatial import distance

# initializing points in
# numpy arrays
point1 = (4, 4, 2)
point2 = (1, 2, 1)
 
# print Euclidean distance 
print(distance.euclidean(point1,point2))

3.7416573867739413


### Z-Score calculation

In order to calculate the z-score, we need to first calculate the mean and the standard deviation of an array

In [27]:
values = [4,5,6,6,6,7,8,12,13,13,14,18]
# Calculate the Standard Deviation in Python

mean = sum(values) / len(values)
differences = [(value - mean)**2 for value in values]
sum_of_differences = sum(differences)
standard_deviation = (sum_of_differences / (len(values) - 1)) ** 0.5

print(standard_deviation)
# Returns: 1.3443074553223537

zscores = [(value - mean) / standard_deviation for value in values]

print(zscores)

4.458563432181702
[-1.1961999452194811, -0.9719124554908285, -0.7476249657621759, -0.7476249657621759, -0.7476249657621759, -0.5233374760335231, -0.2990499863048704, 0.5980999726097405, 0.8223874623383931, 0.8223874623383931, 1.0466749520670457, 1.9438249109816566]


In [28]:
import scipy.stats as stats
zscores = stats.zscore(values)
print(zscores)

[-1.2493901  -1.01512945 -0.78086881 -0.78086881 -0.78086881 -0.54660817
 -0.31234752  0.62469505  0.85895569  0.85895569  1.09321633  2.0302589 ]
